# Generated by Django 2.2.5 on 2019-10-03 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import minor_project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFormWithFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('upload', models.FileField(blank=True, null=True, upload_to=minor_project.models.ModelFormWithFile.get_user_folder)),
                ('user', models.ForeignKey(default='No_login', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
