# Generated by Django 2.2.5 on 2019-10-03 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minor_project', '0002_auto_20191003_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelformwithfile',
            name='user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
