# Generated by Django 2.2.6 on 2019-10-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_project', '0003_auto_20191003_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelformwithfile',
            name='ques_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
