# Generated by Django 2.2.6 on 2019-10-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_project', '0007_auto_20191014_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwiseinterviewdetail',
            name='interview_no',
            field=models.IntegerField(default=0),
        ),
    ]
